apps/backend/app.py, apps/backend/requirements.txt, fbexample.py
=> Merging Better gen configs into Converting to Firebase

apps/backend/app.py, apps/backend/requirements.txt, fbexample.py, scripts/proof_of_concept/addNumsforConfig.py
Merging Run with configs to main
=> Run with configs Pull Request

.github/workflows/push.yml, .github/workflows/test.yml
... and are marking our otherwise fine pull requests as not working.
=> Disable outdated CI tasks that no longer assist us

apps/backend/app.py, apps/frontend/components/Dashboard.js, apps/frontend/components/NewExp.js, apps/frontend/firebase/db.js, apps/frontend/pages/dashboard.js, fbexample.py, services/supabase/docker-compose.yml
Finished up Return Results should be good to merge now,
Also deleted a lot of commented code that I ran upon
=> Merge Return Results

apps/backend/app.py
Removed Unused Code and Imports, A lot of the unused code had already been reimplemented in the backend elsewhere to better fit our system. So there wasn't anything that we should've kept and even if we want to see what it used to be we can timetravel
=> Cleaned Up Backend

apps/backend/app.py, apps/frontend/pages/dashboard.js
There was an infinite callback on dashboard causing there to be 55k reads from the frontend. So that's now been fixed
=> Emergency Fix!!!

deployed-restart.sh
Also check out the docs changes https://github.com/AutomatingSciencePipeline/Monorepo/wiki/Connecting-To-Glados#server-maintenance
=> Script to run to reduce the steps required to deploy to Glados

apps/backend/backend.Dockerfile, apps/frontend/frontend.Dockerfile, apps/frontend/next.config.js, apps/frontend/pages/dashboard.tsx, docker-compose.dev.yml, docker-compose.yml
TWO hot reloads in one day*?
<https://www.youtube.com/watch?v=a4ee14ubeA0>
*roughly
=> Frontend hot reload + frontend real™ actual™ production server

apps/backend/app.py, apps/frontend/components/NewExp.tsx, apps/frontend/pages/api/queue.tsx, apps/frontend/pages/dashboard.tsx
Check from the frontend how many experiments are enqueued (or see if the server is down)
Manual button for now because setInterval is being weird (maybe hot reloading's fault)
=> Status query

.github/workflows/node-test.yml, apps/frontend/package.json
https://github.com/vercel/next.js/discussions/14234
=> CI task to run typescript type checking

apps/backend/app.py, apps/backend/modules/runner.py
Remove extra printing of log message
=> Clarify variable names, more verbose error logging when Trial's Extra File missing

apps/backend/app.py
Documentation is in the style of JavaDocs (hopefully...)
=> Added documentation to the main backend file

.github/workflows/docker.yml, apps/backend/app.py
Just opening this PR so the CI runs
=> Ci builds dev too

apps/frontend/frontend.Dockerfile, apps/frontend/package.json
This is from the Spring and I forgot to PR it
It's not needed, and somehow wasn't being installed in the container for one person?
=> Remove usage of cross-env

apps/backend/app.py, apps/frontend/components/flows/ViewExperiment/ExperimentListing.tsx, apps/frontend/firebase/db.ts, apps/frontend/pages/api/experiments/[expIdToStart].tsx, apps/frontend/pages/dashboard.tsx
Added a Delete button and fixed spelling errors on comments.
Potential todo: add confirmation for delete
=> On boarding delete experiment

apps/backend/app.py
Added the remove_downloaded_directory. 10/11/23
=> Pushing the Code

apps/backend/job-runner.yaml, apps/frontend/app/components/Parameter.tsx, apps/frontend/app/components/auth/SignInModal.tsx, apps/frontend/app/components/auth/SignUpModal.tsx, apps/frontend/app/components/flows/AddExperiment/NewExperiment.tsx, apps/frontend/app/components/flows/AddExperiment/stepComponents/DispatchStep.tsx, apps/frontend/app/components/flows/AddExperiment/stepComponents/ParamStep.tsx, apps/frontend/package-lock.json, apps/frontend/package.json, apps/frontend/utils/validators.ts, apps/runner/modules/configs.py
This implementation of string list assumes that the exp is going to be run with all strings that are included in the list. Will discuss with Jason about more specific functionality with default values later.
NOTE: This did upgrade Mantine Forms from v4 to v7
=> String List Base Implementation and Fix Dispatch Step Button

apps/runner/Pipfile, apps/runner/Pipfile.lock, apps/runner/runner.py, example_experiments/python/addNumsWithNumpy.py
=> Allow python files to import packages

apps/frontend/app/components/flows/ViewExperiment/Chart.tsx, apps/frontend/app/components/flows/ViewExperiment/ExperimentListing.tsx
=> Fix charts

apps/frontend/app/components/flows/ViewExperiment/ExperimentListing.tsx, apps/runner/runner.py
=> FEATURE: Add Avg and Total runtimes to Experiment Listing

development_scripts/local/setup_local.py
=> Improve the launch script

apps/frontend/app/components/flows/ViewExperiment/ExperimentListing.tsx, apps/frontend/app/dashboard/page.tsx
Now when renaming an experiment, a checkmark and X appear which correspond to updating the experiment name.
=> Improvement: Made Renaming Experiments more Intuitive

apps/frontend/app/components/flows/ViewExperiment/Chart.tsx
Reverts AutomatingSciencePipeline/Monorepo#489
=> Revert "459 visible columns reset after changing settings 03"

apps/frontend/app/components/flows/ViewExperiment/Chart.tsx
=> sorting should work now

.devcontainer/devcontainer.Dockerfile, .devcontainer/devcontainer.json
This was implemented to make the dev container function properly on glados-forge.
=> Update dev container

helm_packages/nginx-ingress-helm/glados-frontend-ingress.yaml, kube_config/ipaddresspool.yaml, kube_config/kubeadm-config.yaml, kube_config/l2advertisement.yaml
Update kube_config files to make sure that they match what is in production
=> Kube Config Fixes
